### PR TITLE
Filter results by date using tkcalendar

### PR DESCRIPTION
**Pull request by RadoslavK1**
# Description

contains 2 fields for 'from' and 'to' fields 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A - open app, load inbox, select dates from-to. Default year is 2020, so all messages will be shown unless specified otherwise. Press Save, Upload messages - results will be filtered by the date requirements.
- [ ] Test B - open settings, change dates, save, after pressing Upload messages - new results will be shown.

### CODE REVIEW

**Comment by Kubis10** [comment]
Hi thanks for pr but I encountered one error when attempting to open settings inside app:
`
Exception in Tkinter callback
Traceback (most recent call last):
  File "\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "CounterForMessenger\Main.py", line 175, in <lambda>
    padding=5, command=lambda: SettingsPopup(self.controller)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CounterForMessenger\Main.py", line 527, in __init__
    load_from_date=datetime.strptime(self.controller.get_from_date_entry(),"%Y-%m-%d") if not isinstance(self.controller.get_from_date_entry(),date) else self.controller.get_from_date_entry()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not tuple
`

**Comment by RadoslavK1** [comment]
Interesting, could you please tell me steps to reproduce? I'm opening settings and changing dates left and right and there are no errors popping up for me.

**Comment by RadoslavK1** [comment]
I found the issue. Please try it again now. The default data inserted by tkcalendar was in different format.

**Comment by Kubis10** [comment]
Now working thanks!, Conversation loading is a bit slower, but it is acceptable.

**Review by Kubis10 — APPROVED** [review]

**Comment by RadoslavK1** [comment]
Glad it's working. I can look into speeding it up later once I have a bit more free time.

**Pull request merged**
